// -- list of all interactive elements
export const interactiveElements = [
  'button:not(.fx-button) *',
  'button:not(.fx-button) *',
  '.icon-div',
  '.icon-div *',
  '.vid-player *',
  '.vid-light',
  '.vid-light *',
  '.main-player',
  '.main-player *',
  '.fx-wheel-no-fx',
  '.close',
  '.close *',
  '.fx-no',
  '.fx-no *',
  '[href]:not(.playlist-item)',
  'input',
  'select',
  'textarea',
  '[tabindex]:not([tabindex="-1"])',
];
